# This is a basic workflow that is manually triggered

name: Add new Pokemon

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Name of the pokemon to create'
        # Input has to be provided for the workflow to run
        required: true
      type:
        description: 'Type of the pokemon to create'
        # Input has to be provided for the workflow to run
        required: true
      image:
        description: 'Link to image'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  
  insert:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    - name: test connection
      run: mysql --host=${{ secrets.DB_HOST }} --user=${{ secrets.DB_USER }} --password=${{ secrets.DB_PASSWORD }} --database=${{secrets.DB_NAME}}
    
    # Runs a single command using the runners shell
    - name: insert pokemon
      run: mysql --host=${{ secrets.DB_HOST }} --user=${{ secrets.DB_USER }} --password=${{ secrets.DB_PASSWORD }} --database=${{secrets.DB_NAME}} --execute="insert into pokemon values ('${{ github.event.inputs.name }}','${{ github.event.inputs.type }}','${{ github.event.inputs.image }}')"
