# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
       
    - name: check out repository
      uses: actions/checkout@v3
    
    - name: Setup AWS CLI
      run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        | aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        | aws configure set region ${{ secrets.AWS_REGION }}
        | aws configure set output json
        
    - name: test AWS connection
      run: aws s3 ls

    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
  
    - name: install node
      run: npm install
      
    - name: build
      run: npm run build
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        
    
    - name: publish
      run: aws s3 cp --recursive public/ ${{ AWS_S3_LOCATION }} --cache-control 'public, max-age=300, s-maxage=315360000'
        | aws cloudfront create-invalidation --paths '/*' --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}

