# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    
    - name: Setup AWS CLI
    - run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
    - run: aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - run: aws configure set region ${{ secrets.AWS_REGION }}
    - run: aws configure set output json
    
    
    - uses: actions/checkout@v3
    - name: build
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run build
        

    
    - name: publish
    - run: aws s3 cp --recursive public/ s3://jamstack-public/ --cache-control 'public, max-age=300, s-maxage=315360000'
    - run: aws cloudfront create-invalidation --paths '/*' --distribution-id E11BSNHWM09WR

